.PHONY: clean distclean build run article

export PATH := $(shell npm bin):$(PATH)
export NODE_ENV ?= development

# source file extensions to process
EXTENSIONS = js jsx pug

SOURCE_FILES := $(subst ./,,$(foreach ext,$(EXTENSIONS),$(shell find . -name "*.$(ext)" -not -path "./build/*" -not -path "./node_modules/*" -not -path "./webpack.config.js" -not -path "./public/*" -print)))
JSON_SOURCE_FILES := $(subst ./,,$(shell find . -name "*.json" -not -path "./build/*" -not -path "./node_modules/*" -not -path "./public/*" -print))

COMPILED_FILES := $(addprefix build/, $(addsuffix .js,$(basename $(SOURCE_FILES))) $(JSON_SOURCE_FILES))

PORTS_FILES := $(addprefix ports/, $(shell mongroup names))

SHA_FILE := $(addprefix .git/, $(shell git symbolic-ref HEAD))

build: public/build.js build/sha.js $(COMPILED_FILES)


article:
	@./create-article.sh

ports/%:
	@mkdir -p $(dir $@)
	@mongroup restart $*
	@while [ ! -f $@ ]; do sleep 1; done

nginx/%.conf: nginx/%.conf.pre $(PORTS_FILES)
	@echo "$@: Generating nginx config file"
	@echo "# DO NOT EDIT THIS FILE, INSTEAD EDIT: $<" > "$@"
	@m4 \
		-DDIRNAME=$(realpath $(dir $<)) \
		-DFILENAME=$(join $(realpath $(dir $<)),/$(notdir $@)) \
		< "$<" \
		>> "$@"

# JSON files are a special-case, just copy them over as-is:
#   Node.js can load them by default
#   Webpack can use "json-loader"
build/%.json: %.*
	@mkdir -p $(dir $@)
	@echo "$<: JSON source file"
	@cat "$<" > "$@"

# Source files that need to be compiled into regular .js files.
# Optionally, a `build/%.js.map` file may be created with Source
# Map information mapping back to the source.
build/%.js: %.* build/sha.js
	@mkdir -p $(dir $@)
	@case "$(suffix $<)" in \
		.js) echo "$<": JS source file && \
			babel "$<" --out-file "$@" --source-maps \
			;; \
		.jsx) echo "$<": JSX source file && \
			babel --presets react "$<" --out-file "$@" --source-maps \
			;; \
		.pug) echo "$<": PUG source file && \
			pug --client < "$<" > "$@" && \
			echo "module.exports = template;" >> "$@" \
			;; \
		esac

# Requireable access to the latest git commit SHA
build/sha.js: $(SHA_FILE)
	@mkdir -p $(dir $@)
	@echo "sha.js: Generating git HEAD SHA file"
	@echo "module.exports = '$(shell cat "$<")';" > "$@"

public/build.js: package.json $(COMPILED_FILES)
	@mkdir -p $(dir $@)
	@webpack # config is in `webpack.config.js`

clean:
	@rm -rfv nginx/*.conf build public/build.*

distclean:
	@rm -rfv node_modules
