.PHONY: clean distclean build run article

export PATH := $(shell npm bin):$(PATH)
export NODE_ENV ?= development

# nginx config settings for the preprocessor
PORT ?= 3000
SERVER_NAME ?= n8.io.localhost

# source file extensions to process
EXTENSIONS = js jsx json

SOURCE_FILES := $(subst ./,,$(foreach ext,$(EXTENSIONS),$(shell find . -name "*.$(ext)" -not -path "./build/*" -not -path "./node_modules/*" -not -path "./webpack.config.js" -not -path "./public/*" -print)))

COMPILED_FILES := $(addprefix build/, $(addsuffix .js,$(basename $(SOURCE_FILES))))

PORTS_FILES := $(addprefix ports/, $(shell mongroup names))


build: public/build.js nginx/server.conf $(COMPILED_FILES)

article:
	@./create-article.sh

ports/%:
	@mongroup restart $*
	@while [ ! -f $@ ]; do sleep 1; done


nginx/%.conf: nginx/%.conf.pre $(PORTS_FILES)
	@echo "# DO NOT EDIT THIS FILE, INSTEAD EDIT: $<" > "$@"
	@m4 \
		-DPORT=$(PORT) \
		-DSERVER_NAME=$(SERVER_NAME) \
		-DDIRNAME=$(realpath $(dir $<)) \
		-DFILENAME=$(join $(realpath $(dir $<)),/$(notdir $@)) \
		< "$<" \
		>> "$@"

build/%.js: %.*
	@mkdir -p $(dir $@)
	@case "$(suffix $<)" in \
		.js) echo "$<": JS source file && \
			babel "$<" --out-file "$@" --source-maps \
			;; \
		.jsx) echo "$<": JSX source file && \
			babel --presets react "$<" --out-file "$@" --source-maps \
			;; \
		.json) echo "$<": JSON source file && \
			printf "module.exports = " > "$@" && \
			node -pe "require('fs').readFileSync('$(abspath $<)', 'utf8').trim()" >> "$@" \
			;; \
		esac

public/build.js: package.json $(COMPILED_FILES)
	@mkdir -p $(dir $@)
	@webpack # config is in `webpack.config.js`

clean:
	@rm -rfv nginx/*.conf build public/build.* ports/*

distclean:
	@rm -rfv node_modules
